-- Applied atomically by scripts/migrate.js. Existing events are never rewritten.
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    full_name TEXT NOT NULL DEFAULT '',
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'teacher',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Extend a pre-existing users table without recreating IDs or deleting rows.
-- Existing tables must already have a unique id and an email column.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS full_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS password_hash TEXT,
    ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'teacher',
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- Do not silently retain or import a legacy plaintext-password column.
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = current_schema() AND table_name = 'users'
               AND column_name IN ('password', 'plain_password', 'plaintext_password')) THEN
        RAISE EXCEPTION 'Legacy password column detected. Review and remove it through a password-reset migration before running auth migration.';
    END IF;
END $$;

UPDATE users SET is_active = FALSE, password_hash = '!reset-required!'
    WHERE password_hash IS NULL OR password_hash = '';
UPDATE users SET role = 'teacher' WHERE role IS NULL;
UPDATE users SET is_active = FALSE WHERE is_active IS NULL;
UPDATE users SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;

ALTER TABLE users
    ALTER COLUMN email SET NOT NULL,
    ALTER COLUMN password_hash SET NOT NULL,
    ALTER COLUMN role SET NOT NULL,
    ALTER COLUMN role SET DEFAULT 'teacher',
    ALTER COLUMN is_active SET NOT NULL,
    ALTER COLUMN is_active SET DEFAULT TRUE,
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated_at SET NOT NULL,
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP,
    ADD CONSTRAINT fld_users_role_check CHECK (role IN ('admin', 'coordinator', 'teacher')),
    ADD CONSTRAINT fld_users_email_check CHECK (length(btrim(email)) BETWEEN 3 AND 254);
CREATE UNIQUE INDEX fld_users_email_unique ON users (lower(btrim(email)));

CREATE FUNCTION fld_set_updated_at() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = clock_timestamp();
    RETURN NEW;
END $$;
CREATE TRIGGER fld_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION fld_set_updated_at();

-- Match an existing users.id type (e.g. integer, bigint or UUID).
DO $$ DECLARE user_id_type TEXT;
BEGIN
    SELECT format_type(atttypid, atttypmod) INTO user_id_type
    FROM pg_attribute WHERE attrelid = 'users'::regclass AND attname = 'id' AND NOT attisdropped;
    IF user_id_type IS NULL THEN RAISE EXCEPTION 'users.id is required'; END IF;
    EXECUTE format('CREATE TABLE auth_sessions (
        token_hash TEXT PRIMARY KEY CHECK (length(token_hash) = 64),
        user_id %s NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        expires_at TIMESTAMPTZ NOT NULL
    )', user_id_type);
END $$;
CREATE INDEX auth_sessions_user_id_idx ON auth_sessions (user_id);
CREATE INDEX auth_sessions_expires_at_idx ON auth_sessions (expires_at);

-- Revoke sessions even when a trusted operator changes credentials directly in SQL.
CREATE FUNCTION fld_revoke_changed_user_sessions() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM auth_sessions WHERE user_id = NEW.id;
    RETURN NEW;
END $$;
CREATE TRIGGER fld_users_revoke_sessions AFTER UPDATE ON users
    FOR EACH ROW WHEN (OLD.password_hash IS DISTINCT FROM NEW.password_hash
        OR OLD.role IS DISTINCT FROM NEW.role OR OLD.is_active IS DISTINCT FROM NEW.is_active)
    EXECUTE FUNCTION fld_revoke_changed_user_sessions();

CREATE TABLE auth_login_limits (
    bucket_hash TEXT PRIMARY KEY,
    attempts INTEGER NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX auth_login_limits_expires_at_idx ON auth_login_limits (expires_at);

-- Owner-operated Express connections work normally; public Data API roles do not.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_login_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON users, auth_sessions, auth_login_limits FROM PUBLIC;
DO $$ DECLARE api_role TEXT;
BEGIN
    FOREACH api_role IN ARRAY ARRAY['anon', 'authenticated'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = api_role) THEN
            EXECUTE format('REVOKE ALL ON users, auth_sessions, auth_login_limits FROM %I', api_role);
        END IF;
    END LOOP;
END $$;
