-- Empty academic tables only. No demonstration students, homework or grades.
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL CHECK (length(btrim(full_name)) BETWEEN 1 AND 120),
    grade TEXT NOT NULL CHECK (grade IN ('Grade 1', 'Grade 2', 'Grade 3', 'Grade 4')),
    class_name TEXT NOT NULL CHECK (class_name ~ '^[A-G]$'),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX students_class_active_idx ON students (grade, class_name, is_active, full_name, id);
CREATE TRIGGER fld_students_updated_at BEFORE UPDATE ON students
    FOR EACH ROW EXECUTE FUNCTION fld_set_updated_at();

CREATE TABLE homework_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (length(btrim(title)) BETWEEN 1 AND 500),
    description TEXT NOT NULL DEFAULT '' CHECK (length(description) <= 10000),
    grade TEXT NOT NULL CHECK (grade IN ('Grade 1', 'Grade 2', 'Grade 3', 'Grade 4')),
    class_name TEXT NOT NULL CHECK (class_name ~ '^[A-G]$'),
    assign_date DATE NOT NULL,
    due_date DATE NOT NULL CHECK (due_date >= assign_date),
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX homework_class_due_idx ON homework_assignments (grade, class_name, due_date, assign_date);
CREATE TRIGGER fld_homework_updated_at BEFORE UPDATE ON homework_assignments
    FOR EACH ROW EXECUTE FUNCTION fld_set_updated_at();

CREATE TABLE homework_checks (
    homework_id BIGINT NOT NULL REFERENCES homework_assignments(id) ON DELETE RESTRICT,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
    status TEXT NOT NULL CHECK (status IN ('completed', 'partially-done', 'not-done', 'late', 'absent')),
    note TEXT NOT NULL DEFAULT '' CHECK (length(note) <= 2000),
    checked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (homework_id, student_id)
);
CREATE INDEX homework_checks_student_idx ON homework_checks (student_id, homework_id);

-- Preserve compatibility with legacy INTEGER/BIGINT/UUID users.id schemas.
DO $$ DECLARE user_id_type TEXT;
BEGIN
    SELECT format_type(atttypid, atttypmod) INTO user_id_type
        FROM pg_attribute WHERE attrelid = 'users'::regclass AND attname = 'id' AND NOT attisdropped;
    IF user_id_type IS NULL THEN RAISE EXCEPTION 'users.id is required'; END IF;
    EXECUTE format('ALTER TABLE homework_assignments ADD COLUMN created_by %s NOT NULL REFERENCES users(id) ON DELETE RESTRICT', user_id_type);
    EXECUTE format('ALTER TABLE homework_checks ADD COLUMN checked_by %s NOT NULL REFERENCES users(id) ON DELETE RESTRICT', user_id_type);
END $$;
CREATE INDEX homework_created_by_idx ON homework_assignments (created_by);
CREATE INDEX homework_checks_checked_by_idx ON homework_checks (checked_by);

ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE homework_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE homework_checks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON students, homework_assignments, homework_checks FROM PUBLIC;
DO $$ DECLARE api_role TEXT;
BEGIN
    FOREACH api_role IN ARRAY ARRAY['anon', 'authenticated'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = api_role) THEN
            EXECUTE format('REVOKE ALL ON students, homework_assignments, homework_checks FROM %I', api_role);
        END IF;
    END LOOP;
END $$;
