-- One library record can be reused by calendar events and homework.
CREATE TABLE materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (length(btrim(title)) BETWEEN 1 AND 200),
    description TEXT NOT NULL DEFAULT '' CHECK (length(description) <= 5000),
    grades TEXT[] NOT NULL DEFAULT '{}' CHECK (
        array_ndims(grades) IS NULL OR (array_ndims(grades) = 1 AND
        grades <@ ARRAY['Grade 1','Grade 2','Grade 3','Grade 4']::text[] AND array_position(grades, NULL) IS NULL)),
    category TEXT NOT NULL DEFAULT 'Other' CHECK (category IN ('Worksheet','Lesson plan','Presentation','Assessment','Audio','Video','Other')),
    unit TEXT NOT NULL DEFAULT '' CHECK (length(unit) <= 120),
    kind TEXT NOT NULL CHECK (kind IN ('file','link')),
    url TEXT,
    file_name TEXT,
    file_size INTEGER,
    mime_type TEXT,
    storage_key TEXT UNIQUE,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((kind = 'link' AND url IS NOT NULL AND storage_key IS NULL AND file_name IS NULL AND file_size IS NULL AND mime_type IS NULL)
        OR (kind = 'file' AND url IS NULL AND storage_key IS NOT NULL AND file_name IS NOT NULL
            AND file_size BETWEEN 1 AND 10485760 AND mime_type IS NOT NULL))
);
CREATE INDEX materials_grades_idx ON materials USING GIN(grades);
CREATE INDEX materials_active_created_idx ON materials (is_archived, created_at DESC, id);
CREATE TRIGGER fld_materials_updated_at BEFORE UPDATE ON materials
    FOR EACH ROW EXECUTE FUNCTION fld_set_updated_at();

ALTER TABLE events ADD COLUMN grades TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE events ADD CONSTRAINT fld_event_grades CHECK (
    array_ndims(grades) IS NULL OR (array_ndims(grades) = 1 AND
    grades <@ ARRAY['Grade 1','Grade 2','Grade 3','Grade 4']::text[] AND array_position(grades, NULL) IS NULL));
CREATE INDEX events_grades_idx ON events USING GIN(grades);

DO $$ DECLARE user_id_type TEXT; event_id_type TEXT;
BEGIN
    SELECT format_type(atttypid, atttypmod) INTO user_id_type
        FROM pg_attribute WHERE attrelid = 'users'::regclass AND attname = 'id' AND NOT attisdropped;
    SELECT format_type(atttypid, atttypmod) INTO event_id_type
        FROM pg_attribute WHERE attrelid = 'events'::regclass AND attname = 'id' AND NOT attisdropped;
    IF user_id_type IS NULL OR event_id_type IS NULL THEN RAISE EXCEPTION 'An ID column is missing'; END IF;
    EXECUTE format('ALTER TABLE materials ADD COLUMN created_by %s NOT NULL REFERENCES users(id) ON DELETE RESTRICT', user_id_type);
    EXECUTE format('CREATE TABLE event_materials (event_id %s NOT NULL REFERENCES events(id) ON DELETE CASCADE,
        material_id BIGINT NOT NULL REFERENCES materials(id) ON DELETE RESTRICT, PRIMARY KEY(event_id, material_id))', event_id_type);
END $$;
CREATE INDEX materials_created_by_idx ON materials (created_by);
CREATE INDEX event_materials_material_idx ON event_materials (material_id, event_id);
CREATE TABLE homework_materials (
    homework_id BIGINT NOT NULL REFERENCES homework_assignments(id) ON DELETE RESTRICT,
    material_id BIGINT NOT NULL REFERENCES materials(id) ON DELETE RESTRICT,
    PRIMARY KEY (homework_id, material_id)
);
CREATE INDEX homework_materials_material_idx ON homework_materials (material_id, homework_id);

ALTER TABLE materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE homework_materials ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON materials, event_materials, homework_materials FROM PUBLIC;
DO $$ DECLARE api_role TEXT;
BEGIN
    FOREACH api_role IN ARRAY ARRAY['anon', 'authenticated'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = api_role) THEN
            EXECUTE format('REVOKE ALL ON materials, event_materials, homework_materials FROM %I', api_role);
        END IF;
    END LOOP;
END $$;
