CREATE TABLE announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (length(btrim(title)) BETWEEN 1 AND 200),
    description TEXT NOT NULL CHECK (length(btrim(description)) BETWEEN 1 AND 8000),
    category TEXT NOT NULL CHECK (category IN ('General','Meeting','Deadline','Update')),
    date DATE NOT NULL,
    grades TEXT[] NOT NULL DEFAULT '{}' CHECK (fld_valid_grades(grades)),
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DO $$ DECLARE user_id_type TEXT;
BEGIN
    SELECT format_type(atttypid, atttypmod) INTO user_id_type
        FROM pg_attribute WHERE attrelid='users'::regclass AND attname='id' AND NOT attisdropped;
    EXECUTE format('ALTER TABLE announcements ADD COLUMN created_by %s NOT NULL REFERENCES users(id) ON DELETE RESTRICT',user_id_type);
END $$;
CREATE INDEX announcements_created_by_idx ON announcements(created_by);
CREATE INDEX announcements_active_date_idx ON announcements(is_archived, date DESC, id);
CREATE INDEX announcements_grades_idx ON announcements USING GIN(grades);
CREATE TRIGGER fld_announcements_updated_at BEFORE UPDATE ON announcements
    FOR EACH ROW EXECUTE FUNCTION fld_set_updated_at();
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON announcements FROM PUBLIC;
DO $$ DECLARE api_role TEXT;
BEGIN
    FOREACH api_role IN ARRAY ARRAY['anon','authenticated'] LOOP
        IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=api_role) THEN
            EXECUTE format('REVOKE ALL ON announcements FROM %I',api_role);
        END IF;
    END LOOP;
END $$;
